name: Docker
# This builds the docker image and pushes it to DockerHub
# Runs on nf-core repo releases and push event to 'dev' branch (PR merges)
on:
  push:
    branches:
      - main

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Only run for the nf-core repo, for releases and merged PRs
    if: ${{ github.repository == 'evotools/nf-LO' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Build new docker image
        run: docker build --no-cache . -t ${{ secrets.DOCKER_HUB_USERNAME }}/nf-LO:latest

      - name: Push Docker image to DockerHub
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nf-LO:latest
      - name: Push Docker image to DockerHub 
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nf-LO:latest
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/nf-LO:latest nfcore/rnaseq:${{ github.event.release.tag_name }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nf-LO:${{ github.event.release.tag_name }}
